FROM {{.BASE_IMAGE}}:{{.BASE_IMAGE_VERSION}}

RUN mkdir -p /etc/service-center

COPY ./service-center/conf /etc/service-center/conf
COPY ./service-center/service-center /usr/bin/service-center

WORKDIR /etc/service-center

ENTRYPOINT ["service-center"]
