// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	event.proto
	syncer.proto

It has these top-level messages:
	Member
	Discover
	PullRequest
	SyncService
	SyncData
	MapEntry
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	NodeName string `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	RPCPort  int32  `protobuf:"varint,2,opt,name=RPCPort" json:"RPCPort,omitempty"`
	Time     string `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto1.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Member) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Member) GetRPCPort() int32 {
	if m != nil {
		return m.RPCPort
	}
	return 0
}

func (m *Member) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Discover struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	Options     string `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	Time        string `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *Discover) Reset()                    { *m = Discover{} }
func (m *Discover) String() string            { return proto1.CompactTextString(m) }
func (*Discover) ProtoMessage()               {}
func (*Discover) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Discover) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Discover) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *Discover) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto1.RegisterType((*Member)(nil), "proto.Member")
	proto1.RegisterType((*Discover)(nil), "proto.Discover")
}

func init() { proto1.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x41, 0x5c, 0x6c, 0xbe,
	0xa9, 0xb9, 0x49, 0xa9, 0x45, 0x42, 0x52, 0x5c, 0x1c, 0x79, 0xf9, 0x29, 0xa9, 0x7e, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x50, 0x80,
	0x73, 0x40, 0x7e, 0x51, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x8c, 0x2b, 0x24, 0xc4,
	0xc5, 0x52, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0x0c, 0xd6, 0x01, 0x66, 0x2b, 0x45, 0x71, 0x71, 0xb8,
	0x64, 0x16, 0x27, 0xe7, 0x97, 0xa5, 0x16, 0x09, 0x29, 0x70, 0x71, 0x17, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0x23, 0x1b, 0x8c, 0x2c, 0x04, 0x32, 0x3b, 0xbf, 0xa0, 0x24, 0x33, 0x3f, 0xaf, 0x18, 0x6c,
	0x36, 0x67, 0x10, 0x8c, 0x8b, 0xcd, 0xec, 0x24, 0x36, 0xb0, 0xb3, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x00, 0xd3, 0xab, 0xa6, 0xcc, 0x00, 0x00, 0x00,
}
