curl -X POST -H "Content-Type: application/xml" -H "Cache-Control: no-cache" -H "Postman-Token: af9421dd-00a4-754b-33ce-2c30001d3be1" -d '<instance>
    <hostName>lfgy11</hostName>
    <serviceUuid>3c9b7d12-57d1-4105-b6ff-df7b14c1c53b</serviceUuid>
    <ipAddr>10.130.158.159</ipAddr>
    <vipAddress></vipAddress>
    <secureVipAddress></secureVipAddress>
    <status>UP</status>
    <overriddenstatus></overriddenstatus>
    <port>9980</port>
    <securePort>0</securePort>
    <homePageUrl></homePageUrl>
    <statusPageUrl></statusPageUrl>
    <healthCheckUrl>v2/version</healthCheckUrl>
    <countryId>0</countryId>
    <dataCenterInfo>
        <name>MyOwn</name>
        <metadata>
            <ami-launch-index></ami-launch-index>
            <local-hostname></local-hostname>
            <availability-zone></availability-zone>
            <instance-id></instance-id>
            <public-ipv4></public-ipv4>
            <public-hostname></public-hostname>
            <ami-manifest-path></ami-manifest-path>
            <local-ipv4></local-ipv4>
            <hostname></hostname>
            <ami-id></ami-id>
            <instance-type></instance-type>
        </metadata>
    </dataCenterInfo>
    <leaseInfo>
        <renewalIntervalInSecs>0</renewalIntervalInSecs>
        <durationInSecs>0</durationInSecs>
        <registrationTimestamp>0</registrationTimestamp>
        <lastRenewalTimestamp>0</lastRenewalTimestamp>
        <evictionTimestamp>0</evictionTimestamp>
        <serviceUpTimestamp>0</serviceUpTimestamp>
    </leaseInfo>
    <metadata>
        <test>value</test>
    </metadata>
</instance>
' "http://localhost:9980/registry/v2/mservices/3c9b7d12-57d1-4105-b6ff-df7b14c1c53b"