apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: provider
        image: provider:dev
        ports:
        - containerPort: 8081