name: Merge check
on: [ push, pull_request ]
jobs:
  build:
    name: Merge check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.20'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: build
        run: |
          bash -x scripts/build/local.sh
  ut4etcd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.20'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: UT-ETCD
        run: |
          bash -x scripts/ut_test_in_docker.sh etcd
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.20'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: Integration Testing
        run: |
          bash -x scripts/integration_test.sh
